spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: project